### ISSUE TITLE
The database name and location is not clear.

### ISSUE THREAD

**Issue by hvdbrand** [jmforsythe/Git-Heat-Map#11] opened 2023-03-01 07:31 UTC
I tried several runs of generate_db.py and saw the following behavior:
(I run on WIndows, Python 3.8-64 in PowerShell using a venv)
```
(venv) PS C:\Dev\my-repo> python C:\Dev\Tools\Git-Heat-Map\generate_db.py C:\Dev\my-repo\
(venv) PS C:\Dev\my-repo> python C:\Dev\Tools\Git-Heat-Map\generate_db.py C:\Dev\my-repo
```
The first run creates a file `.db` in `C:\Dev\my-repo\`.
I would have liked the file to have a name and an extension, instead of just the extension.
The second run creates a file `my-repo.db` in `C:\Dev\`.

I do not have the idea that one is better than the other, but I would have liked to know which file was generated by looking at the command output. I took me some time to figure out where the db was and how I should run to make it be picked up by the app.

So my request would be: generate the db file with a clear name and report the name and the success in the script.

**Comment by jmforsythe** [comment] 2023-03-01 19:29
I believe the issue was caused by me trying to make my own function to parse paths, it should be fixed now.
I have also added an output line after database generation.

**Closed by jmforsythe** 2023-03-01 19:29 UTC

**Comment by hvdbrand** [comment] 2023-03-03 15:17
Thanks, now the .db file is created in the `Git-Heat-Map` folder and for both cases it is now named `my-repo.db` which is also shown on the command line.
